backend:
  name: github
  repo: putraridho/netlify-cms-tutorial

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: Pages
    label: pages
    files:
      - label: Home Page
        name: home
        file: content/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro Text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
